FROM nvidia/cuda:10.1-cudnn7-devel

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
	python3-opencv ca-certificates python3-dev git wget sudo && \
  rm -rf /var/lib/apt/lists/*



# create a non-root user
ARG USER_ID=1000
RUN useradd -m --no-log-init --system  --uid ${USER_ID} appuser -g sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER appuser
WORKDIR /home/appuser


ENV PATH="/home/appuser/.local/bin:${PATH}"
RUN wget https://bootstrap.pypa.io/get-pip.py && \
	python3 get-pip.py --user && \
	rm get-pip.py

# add dir
COPY requirements.txt /home/appuser
COPY coco.txt /home/appuser

# install
RUN pip install --user -r requirements.txt
# RUN pip install --user -r coco.txt
ENV PILLOW_VERSION=6.2.0

# install dependencies
RUN pip install --user torch torchvision tensorboard
RUN pip install --user 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
RUN pip install --user 'git+https://github.com/facebookresearch/fvcore'
RUN git clone https://github.com/facebookresearch/detectron2 detectron2_repo
ENV FORCE_CUDA="1"
ENV TORCH_CUDA_ARCH_LIST="Kepler;Kepler+Tesla;Maxwell;Maxwell+Tegra;Pascal;Volta;Turing"


# possible fix
# ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX"
ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
ENV CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"


RUN pip install --user -e detectron2_repo
ENV FVCORE_CACHE="/tmp"
WORKDIR /home/appuser/detectron2_repo


# add dir
COPY . /home/appuser/detectron2_repo


# download model
# RUN wget -P /home/appuser/detectron2_repo "https://drive.google.com/file/d/1eayobl8rd6040qCcHI_CrVXHte2RGD_m/view?usp=sharing"


# Make port 80 available to the world outside the container
# EXPOSE 80
ENV PORT 8080
EXPOSE 8080

# Define environment variable
ENV NAME World
ENV GOOGLE_APPLICATION_CREDENTIALS /home/appuser/detectron2_repo/key.json


# EXPOSE 5000
# CMD python app.py
CMD ["python3", "app.py"] 

