FROM python:3.6-slim-stretch

# install stuff
RUN apt update && apt install -y python3-dev unzip gcc libgtk2.0-dev\
                                git curl

# Set the working directory fo /app 
WORKDIR /app

# add dir
COPY requirements.txt /app
COPY coco.txt /app

# install
RUN pip install -r requirements.txt
RUN pip install -r coco.txt
ENV PILLOW_VERSION=6.2.0


# install retinanet
COPY aerial_pedestrian_detection-master /app/aerial_pedestrian_detection-master
RUN cd aerial_pedestrian_detection-master && python setup.py build_ext --inplace && pip install .

# add dir
COPY . /app

# Make port 80 available to the world outside the container
EXPOSE 80
EXPOSE 8080

# Define environment variable
ENV NAME World
ENV GOOGLE_APPLICATION_CREDENTIALS /app/key.json


# EXPOSE 5000
# CMD python app.py
CMD ["python", "app.py"] 

